---

- name: PostgreSQL | Add configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"  # noqa 208
    dest: "{{ pg_config_directory }}/{{ item }}"
    backup: true
  with_items: "{{ pg_config_files }}"
  notify: "{{ pg_handler_on_config_change }}"
  tags: postgresql,postgresql-config

- name: PostgreSQL | Flush handlers
  ansible.builtin.meta: flush_handlers
  tags: postgresql,postgresql-config
