---

- name: restart postgresql
  ansible.builtin.systemd:
    name: "{{ pg_service }}"
    state: restarted
    daemon_reload: true

- name: reload postgresql
  ansible.builtin.systemd:
    name: "{{ pg_service }}"
    state: reloaded
    daemon_reload: true
