# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}



RUN if [ $(command -v apt-get) ]; then \
          apt-get update && \
          apt-get install -y python3 sudo bash ca-certificates gnupg  systemd systemd-sysv  \
          $(if apt-cache search '^python$' | grep -o -m 1 python; then echo python; fi) && \
          apt-get clean; \
    elif [ $(command -v dnf) ]; then \
          cd /etc/yum.repos.d/ & \
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* & \
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* & \
          dnf update & dnf makecache && \
          dnf --assumeyes install python3 sudo python36-devel python3-dnf bash systemd && dnf clean all; \
    elif [ $(command -v yum) ]; then \
          yum makecache fast && \
          yum install -y python sudo yum-plugin-ovl bash systemd systemd-sysv && \
          sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    fi
