# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.image is regex('stretch') %}
    {% set distro = "stretch" %}
{% endif %}

RUN if [ $(command -v apt-get) ]; then \
          {% if distro is defined %}
            echo "deb http://archive.debian.org/debian/ {{ distro }} main contrib non-free" > /etc/apt/sources.list && \
            echo "deb-src http://archive.debian.org/debian/ {{ distro }} main contrib non-free" >> /etc/apt/sources.list && \
            echo "deb http://archive.debian.org/debian-security {{ distro }}/updates main contrib non-free" >> /etc/apt/sources.list && \
            echo "deb-src http://archive.debian.org/debian-security {{ distro }}/updates main contrib non-free" >> /etc/apt/sources.list && \
            echo "deb http://archive.debian.org/debian/ {{ distro }}-backports main contrib non-free" >> /etc/apt/sources.list && \
            echo "deb-src http://archive.debian.org/debian/ {{ distro }}-backports main contrib non-free" >> /etc/apt/sources.list && \
          {% endif %}
          apt-get update && \
          apt-get install -y python3 sudo bash ca-certificates gnupg  systemd systemd-sysv &&\
          apt-get clean; \
    elif [ $(command -v dnf) ]; then \
          cd /etc/yum.repos.d/ & \
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* & \
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* & \
          dnf update & dnf makecache && \
          dnf --assumeyes install python3 sudo python36-devel python3-dnf bash systemd && dnf clean all; \
    elif [ $(command -v yum) ]; then \
          yum makecache fast && \
          yum install -y python sudo yum-plugin-ovl bash systemd systemd-sysv && \
          sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    fi
