---
dependency:
  name: galaxy
driver:
  name: docker

lint: |
    yamllint .
    ansible-lint .

platforms:
  - name: postgres
    image: ${DOCKER_BASE_IMAGE:-debian:bookworm-slim}
    privileged: false
    exposed_ports:
      - 80/tcp
      - 9100/tcp
      - 5432/tcp
    published_ports:
      - 0.0.0.0:5432:5432/tcp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - '/var/run/docker.sock:/var/run/docker.sock'
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    groups:
      - pggroup
    tmpfs:
      - '/tmp'
      - '/run'
      - '/run/lock'
    command: '/lib/systemd/systemd'

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      pggroup:
        pg_major_release: ${PG_MAJOR_RELEASE:-17}
        pg_os_tuning: false
        pg_users_no_log: false
        pg_users:
          - name: example_user
            password: supersecure
        pg_databases:
          - name: example_db
scenario:
  name: default

verifier:
  name: ansible
